apiVersion: apps/v1
kind: Deployment
metadata:
  name: 721demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 721demo
  template:
    metadata:
      labels:
        app: 721demo
    spec:
      containers:
      - name: 721demo
        image: 721demo
        ports:
        - containerPort: 80

